name: Trigger Workflows

on:
  workflow_dispatch: #Using https://console.cron-job.org

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Trigger nightly build
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'trigger-nightly',
              client_payload: {}
            })

      - name: Trigger keep alive
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'trigger-keep-alive',
              client_payload: {}
            })
